import type { Category, AudienceTag, SubArea, EventItem } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "Workshops", slug: "workshops" },
  { id: "c2", name: "Seminars", slug: "seminars" },
  { id: "c3", name: "University Events", slug: "university-events" },
  { id: "c4", name: "Student Events", slug: "student-events" },
  { id: "c5", name: "Family Events", slug: "family-events" },
  { id: "c6", name: "Weekend Events", slug: "weekend-events" },
  { id: "c7", name: "Concerts", slug: "concerts" },
  { id: "c8", name: "Exhibitions", slug: "exhibitions" },
  { id: "c9", name: "Food Events", slug: "food-events" },
  { id: "c10", name: "Sports", slug: "sports" },
  { id: "c11", name: "Islamic / Community", slug: "islamic-community" },
  { id: "c12", name: "Free Events", slug: "free-events" },
];

export const audienceTags: AudienceTag[] = [
  { id: "t1", name: "Family", slug: "family" },
  { id: "t2", name: "Couples", slug: "couples" },
  { id: "t3", name: "Friends", slug: "friends" },
  { id: "t4", name: "Students", slug: "students" },
  { id: "t5", name: "Professionals", slug: "professionals" },
  { id: "t6", name: "Women-friendly", slug: "women-friendly" },
  { id: "t7", name: "Kids-friendly", slug: "kids-friendly" },
  { id: "t8", name: "Solo-friendly", slug: "solo-friendly" },
  { id: "t9", name: "Budget-friendly", slug: "budget-friendly" },
  { id: "t10", name: "Free Entry", slug: "free-entry" },
  { id: "t11", name: "Indoor", slug: "indoor" },
  { id: "t12", name: "Outdoor", slug: "outdoor" },
];

export const subAreas: SubArea[] = [
  { id: "s1", city: "Dhaka", name: "Gulshan" },
  { id: "s2", city: "Dhaka", name: "Banani" },
  { id: "s3", city: "Dhaka", name: "Dhanmondi" },
  { id: "s4", city: "Dhaka", name: "Uttara" },
  { id: "s5", city: "Dhaka", name: "Mirpur" },
  { id: "s6", city: "Dhaka", name: "Bashundhara" },
  { id: "s7", city: "Dhaka", name: "Mohammadpur" },
  { id: "s8", city: "Dhaka", name: "Tejgaon" },
  { id: "s9", city: "Dhaka", name: "Farmgate" },
  { id: "s10", city: "Dhaka", name: "Motijheel" },
  { id: "s11", city: "Dhaka", name: "Old Dhaka" },
  { id: "s12", city: "Dhaka", name: "Hatirjheel" },
  { id: "s13", city: "Dhaka", name: "Baily Road" },
  { id: "s14", city: "Dhaka", name: "Purbachal" },
  { id: "s15", city: "Dhaka", name: "Dhaka University Area" },
  { id: "s16", city: "Dhaka", name: "Other" },
];

// Helpers to compute current-year dates so listing always shows future events.
const today = new Date();
const thisYear = today.getFullYear();
function dateIn(daysFromNow: number) {
  const d = new Date(today);
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
}
function time(h: number, m = 0) {
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

// Realistic, Dhaka-focused, hand-curated events for fallback rendering.
export const fallbackEvents: EventItem[] = [
  {
    id: "ev-001",
    slug: "design-systems-workshop-dhaka",
    title: "Design Systems Workshop: Building Brand Mechanics",
    description:
      "A hands-on session on constructing type stacks, color tokens, and component libraries for product teams. Includes live critique of submitted work. Bring a laptop.",
    poster_url:
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(3),
    start_time: time(18, 0),
    end_time: time(21, 0),
    city: "Dhaka",
    sub_area: "Gulshan",
    venue_name: "The Light House Cafe",
    area_details: "Level 3, House 12, Road 11, Gulshan 2",
    maps_link: "https://maps.google.com/?q=Gulshan+2+Dhaka",
    categories: ["workshops", "student-events"],
    audience_tags: ["students", "professionals", "budget-friendly"],
    price_type: "paid",
    price_note: "৳1,200 (incl. snack box)",
    organizer_name: "Studio Null",
    organizer_email: "hello@studionull.bd",
    outbound_link: "https://example.com/register/design-systems",
    outbound_button_label: "Register",
    is_featured: true,
    is_recommended: true,
    status: "published",
    expected_attendance: 28,
  },
  {
    id: "ev-002",
    slug: "weekend-jatra-hatirjheel",
    title: "Weekend Jatra — Food, Art & Vinyl at Hatirjheel",
    description:
      "Open-air weekend market with local food stalls, zine tables, and a vinyl listening booth curated by Dhaka record labels. Family-friendly until 9 PM.",
    poster_url:
      "https://images.unsplash.com/photo-1533900298318-6b8da08c5232?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(6),
    start_time: time(15, 0),
    end_time: time(22, 0),
    city: "Dhaka",
    sub_area: "Hatirjheel",
    venue_name: "Hatirjheel East Promenade",
    area_details: "Beside the bridge, entry from Begum Rokeya Sarani side",
    categories: ["weekend-events", "food-events", "free-events"],
    audience_tags: ["family", "friends", "outdoor"],
    price_type: "free",
    organizer_name: "Jatra Collective",
    organizer_social_link: "https://instagram.com/jatra.collective",
    outbound_link: "https://example.com/jatra/weekend",
    outbound_button_label: "Learn More",
    is_featured: true,
    status: "published",
    expected_attendance: 1800,
  },
  {
    id: "ev-003",
    slug: "seminar-bangladesh-fintech-2026",
    title: "Seminar: The Next Decade of Bangladesh Fintech",
    description:
      "A panel discussion with founders, regulators, and infra engineers on cards, payments, and embedded finance. Q&A + open mic after.",
    poster_url:
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(9),
    start_time: time(19, 0),
    end_time: time(21, 30),
    city: "Dhaka",
    sub_area: "Banani",
    venue_name: " Auditorium, IBA Bhaban",
    area_details: "Kemal Ataturk Avenue, Banani",
    categories: ["seminars", "university-events"],
    audience_tags: ["students", "professionals", "indoor"],
    price_type: "free",
    organizer_name: "Dhaka Tech Assembly",
    outbound_link: "https://example.com/fintech-seminar",
    outbound_button_label: "Register",
    is_recommended: true,
    status: "published",
    expected_attendance: 320,
  },
  {
    id: "ev-004",
    slug: "du-cultural-night",
    title: "DU Cultural Night — Spring Cycle",
    description:
      "Student-led performances: theatre, slam poetry, fusion band sets, and a closing set from the campus beatboxing society.",
    poster_url:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(11),
    start_time: time(17, 0),
    end_time: time(22, 0),
    city: "Dhaka",
    sub_area: "Dhaka University Area",
    venue_name: "TSC Ground",
    area_details: "Dhaka University campus, opposite Jagannath Hall",
    categories: ["university-events", "concerts", "student-events", "free-events"],
    audience_tags: ["students", "friends", "budget-friendly"],
    price_type: "free",
    organizer_name: "DU Cultural Society",
    outbound_link: "https://example.com/du-cultural",
    outbound_button_label: "Learn More",
    status: "published",
    expected_attendance: 4000,
  },
  {
    id: "ev-005",
    slug: "saturday-morning-run-purbachal",
    title: "Saturday Morning Run: Purbachal Loop",
    description:
      "10K community run along the Purbachal riverside. Free hydration stations, finisher patches, and a post-run breakfast table.",
    poster_url:
      "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(13),
    start_time: time(6, 30),
    end_time: time(9, 0),
    city: "Dhaka",
    sub_area: "Purbachal",
    venue_name: "Purbachal Riverside Park",
    area_details: "Gate 2, Purbachal",
    categories: ["sports", "weekend-events"],
    audience_tags: ["friends", "outdoor", "solo-friendly"],
    price_type: "free",
    organizer_name: "Dhaka Run Club",
    organizer_social_link: "https://instagram.com/dhak.arunclub",
    outbound_link: "https://example.com/purbachal-run",
    outbound_button_label: "Register",
    status: "published",
    expected_attendance: 460,
  },
  {
    id: "ev-006",
    slug: "art-exhibition-payload-of-memory",
    title: "Exhibition: Payload of Memory — Select Works by Dhaka Artists",
    description:
      "A four-week group show featuring painting, sculpture, and moving image by 14 artists based in Bangladesh and the diaspora.",
    poster_url:
      "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(14),
    end_date: dateIn(35),
    start_time: time(11, 0),
    end_time: time(20, 0),
    city: "Dhaka",
    sub_area: "Dhanmondi",
    venue_name: "K1 Gallery",
    area_details: "Road 7, Dhanmondi",
    categories: ["exhibitions", "family-events"],
    audience_tags: ["family", "indoor"],
    price_type: "free",
    organizer_name: "K1 Collective",
    outbound_link: "https://example.com/k1-show",
    outbound_button_label: "View Official Page",
    status: "published",
    expected_attendance: 2200,
  },
  {
    id: "ev-007",
    slug: "intro-to-printmaking-2-day",
    title: "Two-Day Intro to Risograph Printmaking",
    description:
      "Bring a single A4 idea. Leave with 200 finished posters and a working knowledge of the RISO machine. Materials provided.",
    poster_url:
      "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(16),
    start_time: time(11, 0),
    end_time: time(17, 0),
    city: "Dhaka",
    sub_area: "Tejgaon",
    venue_name: "Print Lab BD",
    area_details: "Industrial Plot 4, Tejgaon",
    categories: ["workshops"],
    audience_tags: ["students", "indoor", "budget-friendly"],
    price_type: "paid",
    price_note: "৳2,500 — includes materials",
    organizer_name: "Print Lab BD",
    outbound_link: "https://example.com/riso-workshop",
    outbound_button_label: "Get Tickets",
    status: "published",
    expected_attendance: 14,
  },
  {
    id: "ev-008",
    slug: "iftar-bazaar-old-dhaka",
    title: "Iftar Bazaar — Old Dhaka Walking Tour & Tasting",
    description:
      "Guided sunset walk through Old Dhaka with curated tastings at six stalls and a closing iftar at a heritage home.",
    poster_url:
      "https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(20),
    start_time: time(16, 30),
    end_time: time(20, 0),
    city: "Dhaka",
    sub_area: "Old Dhaka",
    venue_name: "Meeting Point: Chawkbazar Gate",
    area_details: "Chawkbazar, Old Dhaka",
    categories: ["food-events", "islamic-community"],
    audience_tags: ["family", "friends", "outdoor"],
    price_type: "paid",
    price_note: "৳1,800 — all-inclusive",
    organizer_name: "Heritage Walks BD",
    outbound_link: "https://example.com/iftar-walk",
    outbound_button_label: "Register",
    status: "published",
    expected_attendance: 22,
  },
  {
    id: "ev-009",
    slug: "kids-makers-market-bashundhara",
    title: "Kids' Makers Market + Storytime",
    description:
      "Mini stalls run by kids 6–12 selling crafts, comics, and lemonade. Storytime tent with a rotating slate of local readers.",
    poster_url:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(22),
    start_time: time(10, 0),
    end_time: time(14, 0),
    city: "Dhaka",
    sub_area: "Bashundhara",
    venue_name: "Bashundhara City Courtyard",
    area_details: "Outdoor courtyard, Bashundhara City",
    categories: ["family-events", "free-events"],
    audience_tags: ["family", "kids-friendly", "outdoor", "free-entry"],
    price_type: "free",
    organizer_name: "Minidoo",
    outbound_link: "https://example.com/makers-market",
    outbound_button_label: "Learn More",
    status: "published",
    expected_attendance: 900,
  },
  {
    id: "ev-010",
    slug: "indie-music-night-dhanmondi",
    title: "Indie Music Night — 5 Bands, 1 Stage",
    description:
      "Lineup: Aabir, Sourob, The Pori, Nibir, Half Step Down. Doors 6:30 PM, first set 7. Limited standing room.",
    poster_url:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(25),
    start_time: time(19, 30),
    end_time: time(23, 30),
    city: "Dhaka",
    sub_area: "Dhanmondi",
    venue_name: "The Big Tree",
    area_details: "Road 11, Dhanmondi",
    categories: ["concerts"],
    audience_tags: ["friends", "students", "indoor"],
    price_type: "paid",
    price_note: "৳800 (advance) / ৳1,000 (door)",
    organizer_name: "The Big Tree & Co.",
    outbound_link: "https://example.com/indie-night",
    outbound_button_label: "Get Tickets",
    status: "published",
    expected_attendance: 180,
  },
  {
    id: "ev-011",
    slug: "career-talk-women-in-tech",
    title: "Career Talk: Women in Tech, Five Voices",
    description:
      "Five women engineers and PMs on navigating early-career decisions, switching paths, and building community. Open mic for questions.",
    poster_url:
      "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(27),
    start_time: time(18, 30),
    end_time: time(21, 0),
    city: "Dhaka",
    sub_area: "Uttara",
    venue_name: "Uttara Sector 7 Community Hall",
    area_details: "Sector 7, Uttara",
    categories: ["seminars", "free-events"],
    audience_tags: ["students", "professionals", "women-friendly", "indoor"],
    price_type: "free",
    organizer_name: "Code & Coffee Dhaka",
    outbound_link: "https://example.com/women-in-tech",
    outbound_button_label: "Register",
    status: "published",
    expected_attendance: 140,
  },
  {
    id: "ev-012",
    slug: "weekend-job-fair-motijheel",
    title: "Weekend Job Fair — Motijheel Edition",
    description:
      "Curated stalls from 25 employers across tech, banking, and creative industries. Bring printed resumes; on-the-spot screening.",
    poster_url:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&auto=format&fit=crop&q=80",
    start_date: dateIn(30),
    start_time: time(10, 0),
    end_time: time(17, 0),
    city: "Dhaka",
    sub_area: "Motijheel",
    venue_name: "Bangladesh Shilpakala Academy",
    area_details: "Segun Bagicha",
    categories: ["weekend-events", "free-events"],
    audience_tags: ["students", "professionals", "indoor", "free-entry"],
    price_type: "free",
    organizer_name: "Career BD",
    outbound_link: "https://example.com/job-fair",
    outbound_button_label: "Learn More",
    status: "published",
    expected_attendance: 1500,
  },
];

export function isWeekend(isoDate: string) {
  const d = new Date(isoDate);
  const day = d.getDay();
  return day === 5 || day === 6 || day === 0; // Fri, Sat, Sun
}