// Realistic Bangladesh-flavored sample data for fallback rendering.
// Excluded from analytics (see lib/api.ts).
// Used when FastAPI backend is unreachable.

import type { Event, Lookups, Submission } from "./types";
import { CATEGORIES, AUDIENCE_TAGS, SUB_AREAS } from "./categories";

export const FALLBACK_LOOKUPS: Lookups = {
  categories: CATEGORIES.map((c) => ({ ...c })),
  audience_tags: AUDIENCE_TAGS.map((t) => ({ ...t })),
  sub_areas: SUB_AREAS.map((s) => ({ ...s })),
  cities: ["Dhaka"],
};

// Helper for ISO dates relative to "today" — fallback data should always show
// upcoming events. Since this is static, we generate dates relative to file build.
function offsetDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function offsetDateTime(days: number, hours = 0, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

// Posters — Unsplash photos. Editorial, real-world imagery.
// Each event uses a UNSPLASH photo (free to use).
const POSTERS = {
  pottery:
    "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
  calligraphy:
    "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=1200&q=80",
  nightMarket:
    "https://images.unsplash.com/photo-1555992336-fb0d29498b13?auto=format&fit=crop&w=1200&q=80",
  calligraphy2:
    "https://images.unsplash.com/photo-1604871000636-074fa5117945?auto=format&fit=crop&w=1200&q=80",
  books:
    "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=1200&q=80",
  folkMusic:
    "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&w=1200&q=80",
  yoga:
    "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=1200&q=80",
  painting:
    "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80",
  photography:
    "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=1200&q=80",
  cooking:
    "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&q=80",
  coding:
    "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
  cricket:
    "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
  debate:
    "https://images.unsplash.com/photo-1559223607-a43f990c692c?auto=format&fit=crop&w=1200&q=80",
  architecture:
    "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1200&q=80",
  boat:
    "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
  textiles:
    "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
  vintageMarket:
    "https://images.unsplash.com/photo-1481437156560-3205f6a55735?auto=format&fit=crop&w=1200&q=80",
  meditation:
    "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
} as const;

export const FALLBACK_EVENTS: Event[] = [
  {
    id: "evt-001",
    title: "Hand-Thrown Pottery: A Weekend with the Wheel",
    title_bn: "হাতে গড়া মাটি: চাকার সাথে একটা সপ্তাহান্ত",
    slug: "hand-thrown-pottery-weekend",
    description:
      "A two-day immersion into the slow, grounding craft of wheel-thrown pottery. Beginners welcome — we'll cover wedging, centering, throwing cylinders, bowls, and a small vase, plus an introduction to trimming and basic glazing. Tools, clay, and aprons provided. Take home two of your own pieces after a one-week drying and firing cycle. Limited to twelve seats so everyone gets one-on-one time at the wheel.",
    description_bn:
      "দুই দিনের একটা স্থির, মাটির সাথে মিশে যাওয়া কর্মশালা। নতুনরাও আসতে পারেন — আমরা শিখব ওয়েজিং, সেন্টারিং, সিলিন্ডার-বাটি-ফুলদানি গড়া, ট্রিমিং ও বেসিক গ্লেজিং। যন্ত্র, মাটি, অ্যাপ্রন — সব আমরাই দেব। এক সপ্তাহ শুকিয়ে পোড়ানোর পর আপনার দুটো পিস বাসায় নিয়ে যাবেন। বারোটা সিট, প্রত্যেকে চাকার সামনে একক সময় পাবেন।",
    poster_url: POSTERS.pottery,
    start_date: offsetDate(3),
    start_time: "10:00",
    end_date: offsetDate(4),
    end_time: "16:00",
    city: "Dhaka",
    sub_area: "Dhanmondi",
    venue_name: "Matir Mohor Studio",
    venue_name_bn: "মাটির মোহর স্টুডিও",
    area_details: "House 22, Road 7, beside Lake Park, Dhanmondi",
    maps_link: "https://maps.google.com/?q=Dhanmondi+Lake+Park+Dhaka",
    categories: ["workshops"],
    audience_tags: ["solo-friendly", "indoor", "budget-friendly"],
    price_type: "paid",
    price_note: "৳3,500 per person (includes materials)",
    organizer: {
      name: "Matir Mohor",
      phone: "+880 1700 000001",
      email: "hello@matirmohor.bd",
      social_link: "https://instagram.com/matirmohor",
    },
    outbound_link: "https://forms.gle/example-pottery",
    outbound_button_label: "Register",
    is_featured: true,
    is_recommended: true,
    show_in_hero: true,
    status: "published",
    expected_attendance: 12,
    created_at: offsetDateTime(-14),
    updated_at: offsetDateTime(-2),
  },
  {
    id: "evt-002",
    title: "Arabic Calligraphy: An Evening with the Reed Pen",
    slug: "arabic-calligraphy-evening",
    description:
      "Three hours of focused practice with a traditional qalam. We'll cover the geometry of the script, posture, pressure modulation, and finish with a take-home panel of your name rendered in three classical styles. Reed pens, ink, and paper supplied. Suited for absolute beginners and intermediate practitioners.",
    poster_url: POSTERS.calligraphy,
    start_date: offsetDate(5),
    start_time: "18:30",
    end_time: "21:30",
    city: "Dhaka",
    sub_area: "Gulshan",
    venue_name: "Khat Foundation",
    area_details: "Level 3, Rose Valley, 27 Kemal Ataturk Avenue, Gulshan 2",
    maps_link: "https://maps.google.com/?q=Gulshan+2+Dhaka",
    categories: ["workshops", "islamic-community"],
    audience_tags: ["indoor", "solo-friendly", "budget-friendly"],
    price_type: "paid",
    price_note: "৳1,200 (materials included)",
    organizer: {
      name: "Khat Foundation",
      email: "learn@khat.org.bd",
      social_link: "https://instagram.com/khatfoundation",
    },
    outbound_link: "https://khat.org.bd/workshops",
    outbound_button_label: "Register",
    is_featured: true,
    is_recommended: false,
    show_in_hero: true,
    status: "published",
    expected_attendance: 18,
    created_at: offsetDateTime(-10),
    updated_at: offsetDateTime(-1),
  },
  {
    id: "evt-003",
    title: "Hatirjheel Night Market — Spring Edition",
    slug: "hatirjheel-night-market-spring",
    description:
      "The lakeside returns to its weekend rhythm. Forty-plus local makers, vintage sellers, and small-batch food vendors ringed along the eastern promenade. Expect hand-stitched kantha, freshly grilled chotpoti, and live baul from the open-mic tent. Entry is free; come hungry and with cash.",
    poster_url: POSTERS.nightMarket,
    start_date: offsetDate(7),
    start_time: "17:00",
    end_time: "23:00",
    city: "Dhaka",
    sub_area: "Hatirjheel",
    venue_name: "Hatirjheel East Promenade",
    area_details: "Begunbari end, near the cable-stayed footbridge",
    categories: ["food-events", "weekend-events", "free-events"],
    audience_tags: ["family", "friends", "outdoor", "free-entry"],
    price_type: "free",
    organizer: {
      name: "Hatirjheel Collective",
      social_link: "https://instagram.com/hatirjheelcollective",
    },
    outbound_link: "https://facebook.com/hatirjheelcollective",
    outbound_button_label: "Learn More",
    is_featured: true,
    is_recommended: true,
    show_in_hero: true,
    status: "published",
    created_at: offsetDateTime(-21),
    updated_at: offsetDateTime(-3),
  },
  {
    id: "evt-004",
    title: "Bengali Manuscript Illumination — Five Sundays",
    slug: "bengali-manuscript-illumination",
    description:
      "A five-session workshop tracing the visual lineage of Bengali manuscript art — from Pala-period palm leaves to 19th-century kalighat pat. Each Sunday covers a distinct tradition with hands-on practice. The final session includes a public exhibition of participant work at the studio. Materials, tea, and snacks included.",
    poster_url: POSTERS.calligraphy2,
    start_date: offsetDate(10),
    start_time: "15:00",
    end_time: "18:00",
    city: "Dhaka",
    sub_area: "Old Dhaka",
    venue_name: "Alpona Studio",
    area_details: "Near Shakhari Bari, Old Dhaka",
    categories: ["workshops", "exhibitions"],
    audience_tags: ["indoor", "solo-friendly", "professionals"],
    price_type: "paid",
    price_note: "৳6,000 for all five sessions",
    organizer: {
      name: "Alpona Studio",
      email: "studio@alpona.bd",
    },
    outbound_link: "https://alpona.bd/manuscript",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: true,
    show_in_hero: false,
    status: "published",
    expected_attendance: 10,
    created_at: offsetDateTime(-30),
    updated_at: offsetDateTime(-5),
  },
  {
    id: "evt-005",
    title: "Ekushey Book Fair — A Walking Tour with a Publisher",
    slug: "ekushey-book-fair-walking-tour",
    description:
      "A guided two-hour walk through the fair with Nurul Huda, editor at Biddya Prokash. The route covers the major stalls, explains what's new in Bangla publishing this season, and ends with a Q&A over cha at the Bangla Academy canteen. Wear comfortable shoes.",
    poster_url: POSTERS.books,
    start_date: offsetDate(14),
    start_time: "16:00",
    end_time: "18:00",
    city: "Dhaka",
    sub_area: "Dhaka University area",
    venue_name: "Bangla Academy",
    area_details: "Suhrawardy Udyan entrance, near Teacher-Student Centre",
    categories: ["exhibitions", "family-events"],
    audience_tags: ["friends", "students", "budget-friendly"],
    price_type: "paid",
    price_note: "৳500 per person",
    organizer: {
      name: "Boi Barta Walks",
      social_link: "https://instagram.com/boibartawalks",
    },
    outbound_link: "https://boibarta.example/tours",
    outbound_button_label: "Get Tickets",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 20,
    created_at: offsetDateTime(-7),
    updated_at: offsetDateTime(-7),
  },
  {
    id: "evt-006",
    title: "Folk Music Night — Baul, Lalon, and Beyond",
    slug: "folk-music-night-baul-lalon",
    description:
      "An intimate evening of baul and Lalon geeti with Paban Das Baul's ensemble, hosted in a 90-seat heritage home. Sets include traditional baul, Lalon adaptations, and a Q&A on the spiritual lineage of the songs. Doors at 6:30, music at 7.",
    poster_url: POSTERS.folkMusic,
    start_date: offsetDate(6),
    start_time: "19:00",
    end_time: "22:00",
    city: "Dhaka",
    sub_area: "Baily Road",
    venue_name: "Nagar Baul Heritage House",
    area_details: "27 Baily Road, beside Holy Cross school",
    categories: ["concerts", "islamic-community"],
    audience_tags: ["indoor", "couples", "professionals"],
    price_type: "paid",
    price_note: "৳800 advance / ৳1,000 at door",
    organizer: {
      name: "Nagar Baul",
      phone: "+880 1700 000006",
    },
    outbound_link: "https://nagarbaul.example/tickets",
    outbound_button_label: "Get Tickets",
    is_featured: true,
    is_recommended: false,
    show_in_hero: true,
    status: "published",
    expected_attendance: 90,
    created_at: offsetDateTime(-25),
    updated_at: offsetDateTime(-4),
  },
  {
    id: "evt-007",
    title: "Sunday Morning Yoga by the Lake",
    slug: "sunday-morning-yoga-lake",
    description:
      "Slow vinyasa and restorative postures overlooking Dhanmondi Lake. All levels — modifications offered for every shape. Bring your own mat; we bring tea, coffee, and bananas after class. Weather-dependent: cancellation posted by 6am on the day.",
    poster_url: POSTERS.yoga,
    start_date: offsetDate(2),
    start_time: "07:30",
    end_time: "08:45",
    city: "Dhaka",
    sub_area: "Dhanmondi",
    venue_name: "Dhanmondi Lake, west bank",
    area_details: "Entrance beside Abohani Field, Road 8",
    categories: ["sports", "weekend-events"],
    audience_tags: ["solo-friendly", "outdoor", "budget-friendly", "women-friendly"],
    price_type: "free",
    organizer: {
      name: "Shanti Sundays",
      social_link: "https://instagram.com/shantisundays",
    },
    outbound_link: "https://shantisundays.example",
    outbound_button_label: "Learn More",
    is_featured: false,
    is_recommended: true,
    show_in_hero: false,
    status: "published",
    created_at: offsetDateTime(-9),
    updated_at: offsetDateTime(-1),
  },
  {
    id: "evt-008",
    title: "Watercolour Workshop — Painting the Rain",
    slug: "watercolour-workshop-rain",
    description:
      "A four-hour workshop on capturing the soft greys and saturated greens of monsoon Dhaka. We'll work from photographs and quick outdoor sketches. Includes paper, paints, two brushes, and a takeaway kit. Beginners very welcome.",
    poster_url: POSTERS.painting,
    start_date: offsetDate(11),
    start_time: "14:00",
    end_time: "18:00",
    city: "Dhaka",
    sub_area: "Banani",
    venue_name: "Rong Tuli Atelier",
    area_details: "House 41, Road 12, Banani",
    categories: ["workshops"],
    audience_tags: ["indoor", "solo-friendly", "budget-friendly", "women-friendly"],
    price_type: "paid",
    price_note: "৳2,200 (kit included)",
    organizer: {
      name: "Rong Tuli",
      email: "hello@rongtuli.bd",
    },
    outbound_link: "https://rongtuli.bd/workshops",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 14,
    created_at: offsetDateTime(-12),
    updated_at: offsetDateTime(-2),
  },
  {
    id: "evt-009",
    title: "Street Photography Walk — Old Dhaka After Dark",
    slug: "street-photography-old-dhaka",
    description:
      "A guided two-and-a-half-hour photo walk through Old Dhaka's evening streets — led by photographer Mahmud Hossain Opu. We focus on shutter discipline, available light, and candid portraits. Any camera works; phones welcome.",
    poster_url: POSTERS.photography,
    start_date: offsetDate(8),
    start_time: "18:00",
    end_time: "20:30",
    city: "Dhaka",
    sub_area: "Old Dhaka",
    venue_name: "Meet at Shakhari Bari gate",
    area_details: "Old Dhaka, near the Shakhari Bari museum",
    categories: ["workshops", "free-events"],
    audience_tags: ["outdoor", "solo-friendly", "professionals", "free-entry"],
    price_type: "free",
    organizer: {
      name: "Frame Walks BD",
      social_link: "https://instagram.com/framewalksbd",
    },
    outbound_link: "https://framewalks.example/old-dhaka",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 25,
    created_at: offsetDateTime(-15),
    updated_at: offsetDateTime(-1),
  },
  {
    id: "evt-010",
    title: "Hilsa Festival — A Coastal Cooking Class",
    slug: "hilsa-festival-cooking-class",
    description:
      "Three classic preparations of ilish — begun bhaja, doi ilish, and shorshe ilish — taught by home cook Rina Akter. Lunch follows. Allergen note: the menu is fish-forward and not suitable for vegetarians.",
    poster_url: POSTERS.cooking,
    start_date: offsetDate(9),
    start_time: "11:00",
    end_time: "14:00",
    city: "Dhaka",
    sub_area: "Uttara",
    venue_name: "Rina's Kitchen",
    area_details: "Sector 7, Uttara, by the lake",
    categories: ["workshops", "food-events"],
    audience_tags: ["indoor", "friends", "family"],
    price_type: "paid",
    price_note: "৳1,800 per person (lunch included)",
    organizer: {
      name: "Rina Akter",
      phone: "+880 1700 000010",
    },
    outbound_link: "https://rinakitchen.example/hilsa",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: true,
    show_in_hero: false,
    status: "published",
    expected_attendance: 8,
    created_at: offsetDateTime(-11),
    updated_at: offsetDateTime(-2),
  },
  {
    id: "evt-011",
    title: "Code & Coffee — Free Beginner Python Workshop",
    slug: "code-coffee-python-workshop",
    description:
      "Bring a laptop, leave with a working script. This free session covers variables, conditionals, loops, and your first small project (a number-guessing game). Taught by volunteers from the local Python community. Coffee and biscuits provided.",
    poster_url: POSTERS.coding,
    start_date: offsetDate(4),
    start_time: "10:00",
    end_time: "13:00",
    city: "Dhaka",
    sub_area: "Mohammadpur",
    venue_name: "Tech Tonic Cafe",
    area_details: "Town Hall market, Mohammadpur",
    categories: ["workshops", "free-events", "student-events"],
    audience_tags: ["students", "indoor", "budget-friendly", "free-entry", "solo-friendly"],
    price_type: "free",
    organizer: {
      name: "PyDhaka",
      social_link: "https://instagram.com/pydhaka",
    },
    outbound_link: "https://pydhaka.example/python",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 30,
    created_at: offsetDateTime(-8),
    updated_at: offsetDateTime(-2),
  },
  {
    id: "evt-012",
    title: "Mirpur Indoor Cricket League — Open Trials",
    slug: "mirpur-cricket-trials",
    description:
      "Trials for the winter indoor league. All skill levels welcome; we run three divisions. Bring sports shoes and whites if you have them. Spots limited to 80 — first come, first served.",
    poster_url: POSTERS.cricket,
    start_date: offsetDate(6),
    start_time: "08:00",
    end_time: "12:00",
    city: "Dhaka",
    sub_area: "Mirpur",
    venue_name: "Sher-e-Bangla Indoor Net",
    area_details: "Mirpur 10, near the stadium",
    categories: ["sports"],
    audience_tags: ["friends", "outdoor", "budget-friendly"],
    price_type: "free",
    organizer: {
      name: "Dhaka Indoor Cricket",
      phone: "+880 1700 000012",
    },
    outbound_link: "https://dhakacricket.example/trials",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    created_at: offsetDateTime(-20),
    updated_at: offsetDateTime(-6),
  },
  {
    id: "evt-013",
    title: "Parliamentary Debate Open — University Cup Heats",
    slug: "university-debate-cup-heats",
    description:
      "Watch the top eight university debate teams in British Parliamentary format. Motion announced 30 minutes before round one. Snacks available at the venue. Audience seating is free; RSVP recommended.",
    poster_url: POSTERS.debate,
    start_date: offsetDate(12),
    start_time: "13:00",
    end_time: "18:00",
    city: "Dhaka",
    sub_area: "Dhaka University area",
    venue_name: "DU Senate Hall",
    area_details: "University of Dhaka campus",
    categories: ["seminars", "university-events", "student-events", "free-events"],
    audience_tags: ["students", "indoor", "free-entry"],
    price_type: "free",
    organizer: {
      name: "Dhaka University Debating Society",
      social_link: "https://instagram.com/dudebating",
    },
    outbound_link: "https://dudebating.example/cup",
    outbound_button_label: "Learn More",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 200,
    created_at: offsetDateTime(-18),
    updated_at: offsetDateTime(-3),
  },
  {
    id: "evt-014",
    title: "Architectural Heritage Walk — Old Dhaka's Lost Courtyards",
    slug: "architectural-heritage-walk",
    description:
      "A guided half-day walk through Old Dhaka's surviving zamindar baris and hidden inner courtyards, led by architect Iftekhar Ahmed. Includes entry to three private homes rarely open to the public. Comfortable shoes essential.",
    poster_url: POSTERS.architecture,
    start_date: offsetDate(15),
    start_time: "09:00",
    end_time: "13:00",
    city: "Dhaka",
    sub_area: "Old Dhaka",
    venue_name: "Meet at Ahsan Manzil gate",
    area_details: "Kumartuli, Old Dhaka",
    categories: ["exhibitions", "weekend-events"],
    audience_tags: ["friends", "professionals", "outdoor"],
    price_type: "paid",
    price_note: "৳1,500 per person",
    organizer: {
      name: "Iftekhar Ahmed",
      email: "walks@dhakarchitecture.bd",
    },
    outbound_link: "https://dhakarchitecture.example/walks",
    outbound_button_label: "Get Tickets",
    is_featured: false,
    is_recommended: true,
    show_in_hero: false,
    status: "published",
    expected_attendance: 15,
    created_at: offsetDateTime(-22),
    updated_at: offsetDateTime(-5),
  },
  {
    id: "evt-015",
    title: "Buriganga Sunrise Boat Trip",
    slug: "buriganga-sunrise-boat",
    description:
      "A two-hour sunrise boat along the Buriganga — slow pace, life jackets on, tea served onboard. The route passes Sadarghat, the launch terminals, and the quiet stretches upstream. Weather-dependent.",
    poster_url: POSTERS.boat,
    start_date: offsetDate(2),
    start_time: "05:30",
    end_time: "07:30",
    city: "Dhaka",
    sub_area: "Old Dhaka",
    venue_name: "Sadarghat Terminal 3",
    area_details: "Departure from Terminal 3, Sadarghat",
    categories: ["weekend-events", "free-events"],
    audience_tags: ["outdoor", "solo-friendly", "friends", "free-entry"],
    price_type: "free",
    organizer: {
      name: "Nodi Walks",
      social_link: "https://instagram.com/nodiwalks",
    },
    outbound_link: "https://nodiwalks.example/sunrise",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 12,
    created_at: offsetDateTime(-13),
    updated_at: offsetDateTime(-1),
  },
  {
    id: "evt-016",
    title: "Nakshi Kantha — A Stitching Circle",
    slug: "nakshi-kantha-stitching-circle",
    description:
      "Bring your own kantha-in-progress or start a fresh 12x12 inch panel. The host provides tea, thread, and pattern books. Children welcome with a guardian. A relaxed, no-instruction format — show up and stitch.",
    poster_url: POSTERS.textiles,
    start_date: offsetDate(13),
    start_time: "15:30",
    end_time: "18:00",
    city: "Dhaka",
    sub_area: "Tejgaon",
    venue_name: "Shilpi Bari",
    area_details: "Indira Road, Tejgaon",
    categories: ["workshops", "family-events"],
    audience_tags: ["family", "indoor", "women-friendly", "kids-friendly", "budget-friendly"],
    price_type: "paid",
    price_note: "৳300 (covers materials and tea)",
    organizer: {
      name: "Shilpi Bari",
      phone: "+880 1700 000016",
    },
    outbound_link: "https://shilpibari.example/circle",
    outbound_button_label: "Register",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 16,
    created_at: offsetDateTime(-19),
    updated_at: offsetDateTime(-4),
  },
  {
    id: "evt-017",
    title: "Aarong Vintage Pop-Up — Curated by Ketu",
    slug: "aarong-vintage-popup",
    description:
      "A two-day pop-up of vintage saris, hand-loom yardage, and reworked pieces curated by Ketu Studio. Pieces are one-of-a-kind; size and fit details provided at the stall.",
    poster_url: POSTERS.vintageMarket,
    start_date: offsetDate(16),
    start_time: "11:00",
    end_time: "20:00",
    city: "Dhaka",
    sub_area: "Gulshan",
    venue_name: "Alliance Francaise de Dhaka",
    area_details: "26 Mirpur Road, near Dhanmondi (note: cross-check on map)",
    categories: ["exhibitions", "weekend-events"],
    audience_tags: ["friends", "indoor", "couples", "women-friendly"],
    price_type: "free",
    organizer: {
      name: "Ketu Studio",
      social_link: "https://instagram.com/ketustudio",
    },
    outbound_link: "https://ketustudio.example/popup",
    outbound_button_label: "Learn More",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    created_at: offsetDateTime(-24),
    updated_at: offsetDateTime(-6),
  },
  {
    id: "evt-018",
    title: "Morning Meditation — A Quiet Hour",
    slug: "morning-meditation-quiet-hour",
    description:
      "Forty-five minutes of guided sitting (shikantaza-style, with optional breath count), followed by fifteen minutes of tea and informal conversation. Cushions and chairs provided. No experience needed; entry by donation.",
    poster_url: POSTERS.meditation,
    start_date: offsetDate(1),
    start_time: "06:30",
    end_time: "07:45",
    city: "Dhaka",
    sub_area: "Bashundhara",
    venue_name: "Santi Hall",
    area_details: "Block I, Bashundhara R/A",
    categories: ["sports", "free-events"],
    audience_tags: ["indoor", "solo-friendly", "budget-friendly", "free-entry"],
    price_type: "free",
    organizer: {
      name: "Santi Hall Volunteers",
      email: "santi@example.org",
    },
    outbound_link: "https://santihall.example",
    outbound_button_label: "Learn More",
    is_featured: false,
    is_recommended: false,
    show_in_hero: false,
    status: "published",
    expected_attendance: 20,
    created_at: offsetDateTime(-16),
    updated_at: offsetDateTime(-2),
  },
];

// Submissions for admin fallback (mock data so admin has something to review when API is offline)
export const FALLBACK_SUBMISSIONS: Submission[] = [
  {
    id: "sub-001",
    title: "Meena Bazaar — Annual Charity Sale",
    description:
      "Annual charity bazaar with food stalls, games, and handicrafts. Proceeds go to local schools.",
    start_date: offsetDate(20),
    start_time: "11:00",
    end_date: offsetDate(20),
    end_time: "20:00",
    city: "Dhaka",
    sub_area: "Dhanmondi",
    venue_name: "Sunbeams School grounds",
    area_details: "Road 27, Dhanmondi",
    categories: ["family-events", "food-events"],
    audience_tags: ["family", "kids-friendly"],
    price_type: "free",
    organizer: {
      name: "Sunbeams Parents Council",
      phone: "+880 1700 100001",
      email: "bazaar@sunbeams.example",
    },
    outbound_link: "https://sunbeams.example/bazaar",
    wants_promotion_support: true,
    additional_notes: "Would appreciate Instagram story feature.",
    review_status: "submitted",
    created_at: offsetDateTime(-2),
    updated_at: offsetDateTime(-2),
  },
  {
    id: "sub-002",
    title: "Tech Meetup: Building for Bangladesh",
    description:
      "A monthly meetup of product folks and engineers. Lightning talks, no pitch decks.",
    start_date: offsetDate(22),
    start_time: "18:30",
    end_time: "21:00",
    city: "Dhaka",
    sub_area: "Banani",
    venue_name: "Bondstein HQ",
    area_details: "House 12, Road 11, Banani",
    categories: ["seminars", "free-events"],
    audience_tags: ["professionals", "free-entry"],
    price_type: "free",
    organizer: {
      name: "TechBD Collective",
      phone: "+880 1700 100002",
      social_link: "https://instagram.com/techbdcollective",
    },
    outbound_link: "https://techbd.example",
    wants_promotion_support: false,
    review_status: "submitted",
    created_at: offsetDateTime(-1),
    updated_at: offsetDateTime(-1),
  },
];